project:
  type: website
  output-dir: docs

website:
  title: "José Burgos"
  description: "Personal website of José Burgos"
  execute:
    freezer: auto
  navbar:
    background: '#03045e'
    right:
      - about.qmd
      - icon: github
        href: https://github.com/joseburg
      - icon: linkedin
        href: https://www.linkedin.com/in/jos%C3%A9-antonio-burgos-francisco-979672163/
      - icon: envelope-at
        href: joseaburgos01@outlook.com
  

format:
  html:
    clipr: true
    theme: cosmo
    css: styles.css
editor: visual

